#!/bin/bash
#PBS -S /bin/bash
#PBS -q mediumq
#PBS -l select=1:ncpus=60:mem=120gb
#PBS -l walltime=72:00:00
#PBS -P bric
#PBS -N dbcan_global
#PBS -o logs/dbcan_global.out
#PBS -e logs/dbcan_global.err

cd $PBS_O_WORKDIR
mkdir -p logs

module load anaconda3/2022.05
source activate dbcan_env

# --- PATHS ---
BASE_DIR="."
FAA="${BASE_DIR}/global/global.faa"
OUT_DIR="${BASE_DIR}/dbcan_global"
DB="/ibdc-scratch2/home/nipgr001_skmuthappa/Amina/dbcan_db"


mkdir -p "$OUT_DIR"

# --- CHECK INPUT ---
if [ ! -f "$FAA" ]; then
    echo "ERROR: global.faa not found"
    exit 1
fi

echo "Running dbCAN on global proteins..."

# --- RUN DBCAN ---
run_dbcan CAZyme_annotation \
    --input_raw_data "$FAA" \
    --mode protein \
    --db_dir "$DB" \
    --output_dir "$OUT_DIR" \
    --methods diamond,hmm \
    --threads 60


echo "dbCAN annotation complete"
