#!/bin/bash
#PBS -S /bin/bash
#PBS -q mediumq
#PBS -l select=1:ncpus=60:mem=120gb
#PBS -l walltime=72:00:00
#PBS -P bric
#PBS -N eggnog_global
#PBS -o logs/eggnog_global.out
#PBS -e logs/eggnog_global.err

cd $PBS_O_WORKDIR
mkdir -p logs

module load anaconda3/2022.05
source activate eggnog

# --- PATHS ---
BASE_DIR="."
FAA="${BASE_DIR}/global/global.faa"
DB_PATH="${BASE_DIR}/eggnog_db"
OUT_DIR="${BASE_DIR}/eggnog_global"

mkdir -p "$OUT_DIR"

# --- CHECK INPUT ---
if [ ! -f "$FAA" ]; then
    echo "ERROR: global.faa not found"
    exit 1
fi

echo "Running eggNOG on global proteins..."

emapper.py \
    -i "$FAA" \
    --itype proteins \
    -m diamond \
    --sensmode sensitive \
    --cpu 60 \
    --data_dir "$DB_PATH" \
    --output_dir "$OUT_DIR" \
    --output global \
    --tax_scope auto \
    --go_evidence non-electronic \
    --target_orthologs all \
    --seed_ortholog_evalue 0.001 \
    --seed_ortholog_score 60 \
    --override

echo "Finished eggNOG global annotation"
