#!/bin/bash
#PBS -S /bin/bash
#PBS -q mediumq
#PBS -l select=1:ncpus=20:mem=64gb
#PBS -l walltime=24:00:00
#PBS -P bric
#PBS -N coverm_array
#PBS -o logs/coverm.%J_%I.out
#PBS -e logs/coverm.%J_%I.err
#PBS -J 1-6

cd $PBS_O_WORKDIR
mkdir -p logs

# --- ENV ---
module load anaconda3/2022.05
source activate coverm_env

# --- PATHS ---
BASE_DIR="."
BAM_DIR="${BASE_DIR}/bowtie2_mapping_global"
OUT_DIR="${BASE_DIR}/coverm_batches"

mkdir -p "$OUT_DIR"

# --- GET BAM FILES ---
BAMS=($(ls ${BAM_DIR}/*.sorted.bam))

TOTAL=${#BAMS[@]}
BATCH_SIZE=5

START=$(( (PBS_ARRAY_INDEX-1) * BATCH_SIZE ))
END=$(( START + BATCH_SIZE - 1 ))

echo "Batch $PBS_ARRAY_INDEX processing BAMs $START to $END"

SELECTED_BAMS=()

for ((i=START; i<=END && i<TOTAL; i++)); do
    SELECTED_BAMS+=("${BAMS[$i]}")
done

echo "Selected BAMs:"
printf "%s\n" "${SELECTED_BAMS[@]}"

# --- RUN COVERM ---
coverm contig \
    --bam-files "${SELECTED_BAMS[@]}" \
    --methods mean covered_fraction \
    --min-read-percent-identity 95 \
    --min-read-aligned-percent 75 \
    --threads 12 \
    --output-file "${OUT_DIR}/batch_${PBS_ARRAY_INDEX}.tsv" \
    2> "${OUT_DIR}/batch_${PBS_ARRAY_INDEX}.log"

if [ $? -ne 0 ]; then
    echo "ERROR in batch $PBS_ARRAY_INDEX"
    exit 1
fi

echo "Batch $PBS_ARRAY_INDEX done"
